[tool.poetry]
name = "telegram-legal-bot"
version = "0.1.0"
description = "Telegram bot for legal consultations powered by OpenAI GPT"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{ include = "telegram_legal_bot" }]

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "^21.1"
openai = "^1.30"
python-dotenv = "^1.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
